name: Crash
description: The game has a problem when EndlessIDs is present
title: "[Bug]: "
labels: ["bug"]
assignees:
  - falsepattern
body:
  - type: input
    id: modpack
    attributes:
      label: Modpack
      description: You should include the pack's exact name and version here to make debugging easier.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how and when you experience this bug.
    validations:
      required: true