name: Compatibility Request
description: If you tested EndlessIDs with another mod and it crashes or has weird bugs, you can ask for a compatibility patch through this.
title: "[Compatibility Request]: "
labels: ["compat-request"]
assignees:
  - falsepattern
body:
  - type: input
    id: modname
    attributes:
      label: Other mod's name
      description: The name of the other mod
    validations:
      required: true
  - type: input
    id: dist
    attributes:
      label: Other mod's CurseForge/Modrinth/Homepage
      description: Mods on curseforge/modrinth are the easiest to write compat for. A link to the main site where the other mod is hosted is also fine if it's not on these sites. Do not put just a direct download link here.
    validations:
      required: true
  - type: dropdown
    id: license
    attributes:
      label: Other mod's license
      description: What license does the other mod have? (Open source mods are easier to write compatibility patches for)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Game log
      description: Attach the fml-client-latest.log file here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how and when you experience this problem.
    validations:
      required: true